---
- name: Installing the nginx_server on ubuntu
  hosts: nginx_server
  become: yes
  tasks:
    - name: updating the system
      apt:
       update_cache: yes
      become: yes 
    - name: ensure nginx is at the latest version
      apt: 
       name: nginx 
       state: present
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: yes