
---
-name: copy
  hosts: nginx_server
  become: yes  # Use sudo to run commands as root
  tasks:


    - name: Copy files from ansible to remote 
      ansible.builtin.copy:
      src: /opt/zem
      dest: /etc/zem
      owner: root
      group: root
      mode: '0644'

    - name: copy files  from git to remote
      ansible.builtin.git:
      repo: 'https://github.com/ankit20000/DevOpsSRE-PROJECT.git'
      dest: /opt/some_directory