- name: Install Nginx on Ubuntu
  hosts: nginx_server
  become: yes  # Use sudo to run commands as root
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes