f1=open("a.txt","w") 
f1.write("hello this is filehandling")
f2=open("b.txt","w")
f2.write ("this concept is appending")
f2=open("b.txt","r")
data=f2.read()
print(data)
f1= open("a.txt","a")
f1.write(data)